on: push
name: Check Allowed Files
jobs:
  check:
    runs-on: self-hosted
    container:
      image: ghcr.io/sta523-fa21/sta523-base:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Files
      run: |
        checklist::quit_on_failure({
          checklist::check_allowed_files(
            c("proj1.Rmd", "proj1.Rproj", "README.md", "data/*")
          )
        })
        
        checklist::quit_on_failure({
          checklist::check_required_files(
            c("proj1.Rmd", "proj1.Rproj", "README.md")
          )
        })
      shell: Rscript {0}
